apps/user/urls.py
# apps/user/urls.py

# django modules
from django.urls import path

# my modules
from user import views

app_name = "user"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("change-password/", views.change_password, name="change-password"),
    path("profile/", views.profile, name="profile"),
    path("profile-update/", views.profile_update, name="profile-update"),
    path("verify-email/", views.email_verification_request, name="verify-email"),
    path("email/activate/<uidb64>/<token>/", views.email_verifier, name="email-activate"),
]

config/urls.py
# config/urls.py

# Django modules
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as authView

urlpatterns = [
    # user
    path("accounts/", include("user.urls", namespace="user")),

    # main
    path('', include('main.urls', namespace='main')),

    # admin
    path('admin/', admin.site.urls),
    
    # auth: password reset
    path(
        "password_reset/", 
        authView.PasswordResetView.as_view(), 
        name="password_reset"),
    path(
        "password_reset/done/",
        authView.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        authView.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        authView.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),

] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/inc/footer.html
    <footer class="text-center">
        Copyright &#169 ING & Skill_Sets Training, Developed with <span style="color:red;">&hearts;</span> by ING  
    </footer>

templates/inc/header.html
{% load static %}

    <header class="header_wrapper">
        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand" href="/">
                <img src="{% static 'images/logo.png' %}" height="50">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-stream navbar-toggler-icon"></i>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">

                    <ul class="navbar-nav menu-navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="/"><i class="fas fa-home"></i>
                            Home </a>
                        </li>

                        <li class="nav-item">
                            <form action="/i18n/setlang/" method="post" class="d-flex justify-content-center align-items-center">
                                <input type="hidden" name="csrfmiddlewaretoken" value="gEnDBmBPJfQq0gbd3HxAwAbttDAOa0YidWzi1w7Efw6rE50TuvaBT0p2WKOB89kD">
                                <div class="mt-2">
                                    <input name="next" type="hidden" value="">
                                    <select name="language" class="form-select form-select-sm" onchange="this.form.submit()">
                                        <option value="en"  selected>
                                            English (en)
                                        </option>
                                        <option value="hi" >
                                            हिंदी (hi)
                                        </option>
                                    </select>
                                </div>
                            </form>
                        </li>
                    </ul>

                    <!-- dropdown -->
                    <div class="dropdown">
                        {% if request.user.is_authenticated %}
                            <button onclick="myFunction()" 
                                class="dropbtn" 
                                style="border-radius: 4px; border: 1px solid #CED4DA; background: #FFFFFF; color:#2E2529;">
                                {{ user.email }}
                            </button>
                            <div id="myDropdown" class="dropdown-content">
                                <a class="nav-link" href="{% url 'user:logout' %}"><i class="fas fa-sign-in-alt"></i> Logout</a>
                                <a class="nav-link" href="{% url 'user:profile' %}"><i class="fas fa-sign-in-alt"></i> Profile</a>
                                <a class="nav-link" href="{% url 'user:profile-update' %}"><i class="fas fa-sign-in-alt"></i> Profile update</a>
                                <a class="nav-link" href="{% url 'password_reset' %}"><i class="fas fa-sign-in-alt"></i> Password reset</a>
                            </div>
                        {% else %}
                            <button onclick="myFunction()" 
                                class="dropbtn" 
                                style="border-radius: 4px; border: 1px solid #CED4DA; background: #FFFFFF; color:#2E2529;">
                                Login/Signup
                            </button>
                            <div id="myDropdown" class="dropdown-content">
                                <a class="nav-link" href="{% url 'user:login' %}"><i class="fas fa-sign-in-alt"></i> Login</a>
                                <a class="nav-link" href="{% url 'user:signup' %}"><i class="fas fa-plus"></i> Signup</a>
                            </div>
                        {% endif %}
                    </div>
                    <!-- dropdown -->

                </div>
            </div>
        </nav>      
    </header>

templates/inc/messages.html
{% if messages %}
    <div class="container">
        <ul class="messages">
            {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}{% endif %}
                    <h6>{{ message }}</h6>
                </li>
            {% endfor %}
        </ul>
    </div><br><br>

{% endif %}