apps/user/urls.py
# apps/user/urls.py

# django modules
from django.urls import path

# my modules
from user import views

app_name = "user"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("change-password/", views.change_password, name="change-password"),
    path("profile/", views.profile, name="profile"),
    path("profile-update/", views.profile_update, name="profile-update"),
    path("verify-email/", views.email_verification_request, name="verify-email"),
    path("email/activate/<uidb64>/<token>/", views.email_verifier, name="email-activate"),
]

config/urls.py
# config/urls.py

# Django modules
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as authView

urlpatterns = [
    # user
    path("accounts/", include("user.urls", namespace="user")),

    # main
    path('', include('main.urls', namespace='main')),

    # admin
    path('admin/', admin.site.urls),
    
    # auth: password reset
    path(
        "password_reset/", 
        authView.PasswordResetView.as_view(), 
        name="password_reset"),
    path(
        "password_reset/done/",
        authView.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        authView.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        authView.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),

] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/user/models.py
# apps/user/models

# django modules
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.base_user import BaseUserManager
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


# Model: User manager
class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError("The given username must be set")
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


# Model: Custom user
class User(AbstractBaseUser, PermissionsMixin):

    DOCUMENT_CHOICES = [
        (_("Voter Id"), _("Voter ID")),
        (_("Passport"), _("Passport")),
        (_("Citizenship Number"), _("Citizenship Number")),
    ]

    BLOOD_GROUP_CHOICES = [
        ("A+", "A+"),
        ("A-", "A-"),
        ("B+", "B+"),
        ("B-", "B-"),
        ("O+", "O+"),
        ("O-", "O-"),
        ("AB+", "AB+"),
        ("AB-", "AB-"),
    ]


    email = models.EmailField(_("Email Address"), max_length=254, unique=True)
    first_name = models.CharField(_("First Name"), max_length=30, blank=True)
    middle_name = models.CharField(
        _("Middle Name"), max_length=30, null=True, blank=True
    )
    last_name = models.CharField(_("Last Name"), max_length=30, blank=True)
    date_of_birth = models.DateField(
        _("Date of Birth"),
        null=True,
        blank=True,
        help_text="Enter Date in this Format: Year-Month-Day",
    )
    gender = models.CharField(
        _("Gender"), max_length=1, choices=[("M", "Male"), ("F", "Female")], null=True
    )
    blood_group = models.CharField(
        _("Blood Group"), max_length=3, null=True, choices=BLOOD_GROUP_CHOICES
    )
    identity_document_type = models.CharField(
        _("Identity Document Type"), max_length=32, null=True, choices=DOCUMENT_CHOICES
    )
    identity_document_number = models.CharField(
        _("Identity Document Number"), max_length=32
    )
    photo = models.ImageField(
        verbose_name=_("Profile Picture"), upload_to="profileImage/", null=True
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)
    created = models.DateTimeField(_("Last updated"), auto_now=True)
    last_updated = models.DateTimeField(_("Last updated"), auto_now=True)
    is_email_verified = models.BooleanField(_("Email Verified"), default=False)
    is_active = models.BooleanField(_("active"), default=True)
    is_staff = models.BooleanField(_("staff status"), default=False)
    is_superuser = models.BooleanField(_("superuser status"), default=False)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    class Meta:
        verbose_name = "user"
        verbose_name_plural = "users"

    def __str__(self):
        return self.get_full_name()

    def get_full_name(self):
        """
        Returns the full name of user
        """
        return f"{self.first_name} {self.middle_name} {self.last_name}"

    def has_submitted_identity_documents(self):
        """
        Returns true if patient has submitted identity documents
        """
        if (
            self.identity_document_type is None
            and self.identity_document_number is None
        ):
            return False

        return True

apps/user/forms.py
# apps/user/forms.py

# django modules
from django.contrib.auth.forms import (
    UserCreationForm, AuthenticationForm,
    PasswordChangeForm,
)
from django.contrib.auth import get_user_model
from django.forms import ModelForm

User = get_user_model()


# Form: Sign up form
class SignupForm(UserCreationForm):
    """
    Form to create a new user
    """

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

    class Meta:
        model = User
        fields = [
            "email",
            "first_name",
            "middle_name",
            "last_name",
            "date_of_birth",
            "gender",
            "photo",
            "identity_document_type",
            "identity_document_number",
        ]


# Form: Login form
class LoginForm(AuthenticationForm):
    """
    Form to authenticate the user
    """

    # Defin constructor (adding form-control class to each form field)
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

    class Meta:
        model = User
        fields = "__all__"


# Form: Change password form
class ChangePasswordForm(PasswordChangeForm):
    """
    Form to change password
    """

    def __init__(self, *args, **kwargs):
        super(ChangePasswordForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

    class Meta:
        model = User
        fields = "__all__"


# Form: Profile update
class ProfileUpdateForm(ModelForm):
    """
    Form to update the user profile
    """

    def __init__(self, *args, **kwargs):
        super(ProfileUpdateForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

    class Meta:
        model = User
        fields = [
            "first_name",
            "middle_name",
            "last_name",
            "gender",
            "photo",
            "date_of_birth",
            "identity_document_type",
            "identity_document_number",
        ]

apps/user/views.py
# apps/user/views.py

# django modules
from django.http import (
    HttpResponseRedirect,
    HttpResponse,
    HttpResponseForbidden,
    HttpResponseBadRequest,
)
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import (
    authenticate,
    login as user_login,
    logout as user_logout,
    update_session_auth_hash,
)
from django.contrib.auth.decorators import login_required
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_str

import logging
logger = logging.getLogger("django")

# my modules
from user.forms import(
    SignupForm, LoginForm, 
    ChangePasswordForm, ProfileUpdateForm,
)
from user.utils import EmailVerificationTokenGenerator
from user.email import send_email_verification
from user.models import User 

# Create your views here.

# View: Sign up
def signup(request):
    
    """
    Creates a new user based on given email, password and other necessary informations
    """
    
    # 1. Handling POST request
    if request.method == "POST":
        form = SignupForm(request.POST, request.FILES)
        
        # If data from the form is valid
        if form.is_valid():
            user = form.save()
            messages.success(request, 'Account created successfully. Please login')
            return HttpResponseRedirect(reverse('main:home'))

        # If data from the form is NOT valid
        messages.error(request, 'Please enter valid data')
        return render(request, "user/signup.html", {"form": form})
    
    # 2. Handling GET request
    else:
        form = SignupForm()
    
    context = {"form": form}
    
    return render(request, "user/signup.html", context)


# View: Log in
def login(request):
    """
    Login the user if the given email and password are valid
    """

    # 1. Handling POST request
    if request.method == "POST":

        # 1.1 Get sent data from the form
        form = LoginForm(request, request.POST)
        
        # 1.2. Validate sent data

        # 1.2.1. If sent data is valid
        if form.is_valid():
            # 1.2.1.1. Clean data
            email = form.cleaned_data["username"] # refer to custome user
            password = form.cleaned_data["password"]
           
            # 1.2.1.2. Authenticate the email and password
            user = authenticate(email=email, password=password)
            
            # 1.2.1.3 if user exists in db
            if user is not None:
                user_login(request, user)
                logger.info("User Logged in")
                messages.success(request, "Logged in Successfully")
                return HttpResponseRedirect(reverse("main:home"))
            
            # 1.2.1.4. If user is not exists in db
            else:
                logger.error("User is None")
                messages.error(request, "Invalid Login! Please enter correct data")
                return HttpResponseRedirect(reverse("user:login"))
        
        # 1.2.2. If sent data is not valid
        else:
            logger.error("Invalid Username and Passsword")
            messages.error(request, "Please Enter Correct Username and Password")
            return render(request, "user/login.html", {"form": form})
    
    # 2. Handling GET request
    else:
        form = LoginForm()
    
    context = {"form": form}
    
    return render(request, "user/login.html", context)

# View: Log out
def logout(request):
    """
    Logout the user from the current session
    """
    user_logout(request)
    logger.info("Logged out successfully")
    messages.info(request, "Logged out successfully")
    return HttpResponseRedirect(reverse("user:login"))


# View: Log out
def change_password(request):
    """
    Changes the password of the user
    """

    # 1. Handling POST request
    if request.method == "POST":

        # 1.1. Get data sent by the logged in user
        form = ChangePasswordForm(request.user, request.POST)

        # 1.1.1. If sent data is valid
        if form.is_valid():
            # Save data
            form.save()
            # Update session/the form
            update_session_auth_hash(request, form.user)
            # Send messages
            logger.info("Password Changed")
            messages.success(request, "Password Changed Successfully")
            # Redirect user after changing its password
            return HttpResponseRedirect(reverse("user:login"))

        # 1.1.2. If sent data is not valid
        else:
            logger.error("Invalid Data")
            messages.error(
                request, "Unable to change password! Please enter valid data"
            )
            return render(request, "user/change-password.html", {"form": form})

    # 2. Handling GET request
    else:
        form = ChangePasswordForm(request.user)
    
    context = {"form":form}
    
    return render(request, "user/change-password.html", context)


# View: Profile
@login_required
def profile(request):
    # Get user information form the logged in user
    user = request.user
    context = {'user':user}
    return render(request, "user/profile.html", context)


# View: Profile update
def profile_update(request):
    """
    Updates the profile information of user
    """

    # 1. Handling POST request
    if request.method == 'POST':
        # Get data sent by the logged in user
        form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user)

        # If sent data is valid, save it to db and return to user profile
        if form.is_valid():
            form.save()
            logger.info('Profile information updated')
            messages.success(request, 'Profile information updated successfully')
            return HttpResponseRedirect(reverse('user:profile'))

        # If sent data is not valid
        else:
            logger.error('Invalid data')
            messages.error(request, 'Please enter correct data')
            return render(request, 'user/profile-update.html', {'form':form})

    # 2. Handing GET request
    else:
        form = ProfileUpdateForm(instance=request.user)

    context = {'form':form}

    return render(request, "user/profile-update.html", context)


# View: Email verification request
@login_required
def email_verification_request(request):
    """
    Handles the request for email verification
    """
    if not request.user.is_email_verified:
        send_email_verification(request, request.user.id)
        logger.info("Email Verification Link Sent")
        return HttpResponse("Email Verification Link sent to your email address")
    else:
        logger.warning("Email Already Verified")
        return HttpResponseForbidden("Email Already Verified")


# View: Email verifier
def email_verifier(request, uidb64, token):
    """
    Checks the verification link and verifies the user
    """
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user == request.user:
        if EmailVerificationTokenGenerator.check_token(user, token):
            user.is_email_verified = True
            user.save()
            logger.info("Account Verified")
            messages.success(request, "Email Address Verified Successfully")
            return HttpResponseRedirect(reverse("user:profile"))
        else:
            logger.warning("Activation Link is invalid")
            return HttpResponseBadRequest("Activation link is invalid!")
    else:
        return HttpResponseForbidden(
            content="You don't have permission to use this link"
        )

templates/user/change-password.html
<!-- templates/user/change-password -->

{% extends 'base.html' %}
{% block title %}{{ block.super }} Change password {% endblock title %}

{% block content %}

    <div class="container main-content mt-2 p-2">
        <div class="card p-3">
            <div class="card-body">
                <h4>Fill the following details to change your password</h4>
                <form method="POST" action="">
                    {% csrf_token %}

                    {% for field in form %}
                  	<div class="mb-2 row">

                  		<div class="col-sm-2">
                      		{{ field.label_tag }}
                    	</div>

                    	<div class="col-sm-10 col-md-8 col-lg-6">
                      		{{ field }}
                    	</div>

                    	{% if field.help_text %}
                      		<span class="help offset-md-2">{{ field.help_text|safe }}</span>
                    	{% endif %}

                    	{% if form.errors %}
                      		<span class="offset-md-2">{{ field.errors }}</span>
                    	{% endif %}

                  	</div>
                  	{% endfor %}
                    <button type="submit" class="btn btn-primary">Change Password</button>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

templates/user/email-verify.html
<!-- templates/user/email-verify.html -->

{% autoescape off %}  
Hi {{ full_name }},  
Please click on the link to verfy your email,  
http://{{ domain }}{% url 'user:email-activate' uidb64=uid token=token %}  
{% endautoescape %}  

templates/user/login.html
<!-- templates/user/login.hml -->

{% extends 'base.html' %}
{% block title %}{{ block.super }} Log in {% endblock title %}

{% block content %}

    <div class="container main-content mt-2 p-2">
        <div class="card p-3">
            <div class="card-body">
                <h4>Enter your email and password to login</h4>
                <form method="POST" action="">
                    {% csrf_token %}

                    {% for field in form %}
                  	<div class="mb-2 row">

                  		<div class="col-sm-2">
                      		{{ field.label_tag }}
                    	</div>

                    	<div class="col-sm-10 col-md-8 col-lg-6">
                      		{{ field }}
                    	</div>

                    	{% if field.help_text %}
                      		<span class="help offset-md-2">{{ field.help_text|safe }}</span>
                    	{% endif %}

                    	{% if form.errors %}
                      		<span class="offset-md-2">{{ field.errors }}</span>
                    	{% endif %}

                  	</div>
                  	{% endfor %}

                    <button type="submit" class="btn btn-primary">Login</button>
                </form>
            </div>
            
            <p class="p-3">
                <a href="/accounts/password-reset/">Reset Password</a> <br>
                <a href="/accounts/demo-login/" class="btn btn-success">Demo Login (Admin Account)</a>
            </p>
        </div>
    </div>

{% endblock content %}

templates/user/mail-verify.html
<!-- templates/user/email-verify.html -->

{% autoescape off %}  
Hi {{ full_name }},  
Please click on the link to verfy your email,  
http://{{ domain }}{% url 'user:email-activate' uidb64=uid token=token %}  
{% endautoescape %}  

templates/user/profile-update-ori.html
<!-- templates/user/profile-update -->

{% extends 'base.html' %}
{% block title %}{{ block.super }} Profile {% endblock title %}

{% block content %}

    <div class="container main-content mt-2 p-2">
        <div class="m-2 p-2">
            <h4>Fill the following details to update the profile</h4>
            <form method="POST" action="" enctype="multipart/form-data">
                <input type="hidden" name="csrfmiddlewaretoken" value="OSFtC1WbnA5kZuqajB4L6RKMDsR2nckVudOhK9OTqmViMVp3CDSq998P71w6DKnc"> 
                <div class="mb-2 row">
                    <div class="col-sm-2">
                        <label for="id_first_name">First Name:</label>
                    </div>
                    <div class="col-sm-10 col-md-8 col-lg-6">
                        <input type="text" name="first_name" value="super" maxlength="30" class="form-control" id="id_first_name">
                    </div>
                </div>
                <div class="mb-2 row">
                    <div class="col-sm-2">
                        <label for="id_middle_name">Middle Name:</label>
                    </div>
                    <div class="col-sm-10 col-md-8 col-lg-6">
                        <input type="text" name="middle_name" maxlength="30" class="form-control" id="id_middle_name">
                    </div>
                </div>
                <div class="mb-2 row">
                    <div class="col-sm-2">
                        <label for="id_last_name">Last Name:</label>
                    </div>
                    <div class="col-sm-10 col-md-8 col-lg-6">
                        <input type="text" name="last_name" value="user" maxlength="30" class="form-control" id="id_last_name">
                    </div>
                </div>
                <div class="mb-2 row">
                    <div class="col-sm-2">
                        <label for="id_gender">Gender:</label>
                    </div>
                    <div class="col-sm-10 col-md-8 col-lg-6">
                        <select name="gender" class="form-control" required id="id_gender">
                            <option value="" selected>---------</option>
                            <option value="M">Male</option>
                            <option value="F">Female</option>
                        </select>
                    </div>
                </div>
                <div class="mb-2 row">
                    <div class="col-sm-2">
                        <label for="id_photo">Profile Picture:</label>
                    </div>
                    <div class="col-sm-10 col-md-8 col-lg-6">
                        <input type="file" name="photo" accept="image/*" class="form-control" required id="id_photo">
                    </div>
                </div>
                <div class="mb-2 row">
                    <div class="col-sm-2">
                        <label for="id_date_of_birth">Date of Birth:</label>
                    </div>
                    <div class="col-sm-10 col-md-8 col-lg-6">
                        <input type="text" name="date_of_birth" class="form-control" id="id_date_of_birth">
                    </div>
                    <span class="help offset-md-2">Enter Date in this Format: Year-Month-Day</span>
                </div>
                <div class="mb-2 row">
                    <div class="col-sm-2">
                        <label for="id_identity_document_type">Identity Document Type:</label>
                    </div>
                    <div class="col-sm-10 col-md-8 col-lg-6">
                        <select name="identity_document_type" class="form-control" required id="id_identity_document_type">
                            <option value="" selected>---------</option>
                            <option value="Voter Id">Voter ID</option>
                            <option value="Passport">Passport</option>
                            <option value="Citizenship Number">Citizenship Number</option>
                        </select>
                    </div>
                </div>
                <div class="mb-2 row">
                    <div class="col-sm-2">
                        <label for="id_identity_document_number">Identity Document Number:</label>
                    </div>
                    <div class="col-sm-10 col-md-8 col-lg-6">
                        <input type="text" name="identity_document_number" maxlength="32" class="form-control" required id="id_identity_document_number">
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Update Profile</button>
            </form>
        </div>
    </div>

{% endblock content %}

templates/user/signup_ori.html
{% extends 'base.html' %}
{% block title %}{{ block.super }} Sign up {% endblock title %}

{% block content %}

    <div class="container main-content mt-2 p-2">
        <div class="card p-3">
            <div class="card-body">
                <h4>Fill the following details to create a new account</h4>
                <form method="POST" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-2 row">
                        <div class="col-sm-2">
                            <label for="id_email">Email Address:</label>
                        </div>
                        <div class="col-sm-10 col-md-8 col-lg-6">
                            <input type="email" name="email" maxlength="254" autofocus class="form-control" required id="id_email">
                        </div>
                    </div>
                    <div class="mb-2 row">
                        <div class="col-sm-2">
                            <label for="id_first_name">First Name:</label>
                        </div>
                        <div class="col-sm-10 col-md-8 col-lg-6">
                            <input type="text" name="first_name" maxlength="30" class="form-control" id="id_first_name">
                        </div>
                    </div>
                    <div class="mb-2 row">
                        <div class="col-sm-2">
                            <label for="id_middle_name">Middle Name:</label>
                        </div>
                        <div class="col-sm-10 col-md-8 col-lg-6">
                            <input type="text" name="middle_name" maxlength="30" class="form-control" id="id_middle_name">
                        </div>
                    </div>
                    <div class="mb-2 row">
                        <div class="col-sm-2">
                            <label for="id_last_name">Last Name:</label>
                        </div>
                        <div class="col-sm-10 col-md-8 col-lg-6">
                            <input type="text" name="last_name" maxlength="30" class="form-control" id="id_last_name">
                        </div>
                    </div>
                    <div class="mb-2 row">
                        <div class="col-sm-2">
                            <label for="id_date_of_birth">Date of Birth:</label>
                        </div>
                        <div class="col-sm-10 col-md-8 col-lg-6">
                            <input type="text" name="date_of_birth" class="form-control" id="id_date_of_birth">
                        </div>
                        <span class="help offset-md-2">Enter Date in this Format: Year-Month-Day</span>
                    </div>
                    <div class="mb-2 row">
                        <div class="col-sm-2">
                            <label for="id_gender">Gender:</label>
                        </div>
                        <div class="col-sm-10 col-md-8 col-lg-6">
                            <select name="gender" class="form-control" required id="id_gender">
                                <option value="" selected>---------</option>
                                <option value="M">Male</option>
                                <option value="F">Female</option>
                            </select>
                        </div>
                    </div>
                    <div class="mb-2 row">
                        <div class="col-sm-2">
                            <label for="id_photo">Profile Picture:</label>
                        </div>
                        <div class="col-sm-10 col-md-8 col-lg-6">
                            <input type="file" name="photo" accept="image/*" class="form-control" required id="id_photo">
                        </div>
                    </div>
                    <div class="mb-2 row">
                        <div class="col-sm-2">
                            <label for="id_identity_document_type">Identity Document Type:</label>
                        </div>
                        <div class="col-sm-10 col-md-8 col-lg-6">
                            <select name="identity_document_type" class="form-control" required id="id_identity_document_type">
                                <option value="" selected>---------</option>
                                <option value="Voter Id">Voter ID</option>
                                <option value="Passport">Passport</option>
                                <option value="Citizenship Number">Citizenship Number</option>
                            </select>
                        </div>
                    </div>
                    <div class="mb-2 row">
                        <div class="col-sm-2">
                            <label for="id_identity_document_number">Identity Document Number:</label>
                        </div>
                        <div class="col-sm-10 col-md-8 col-lg-6">
                            <input type="text" name="identity_document_number" maxlength="32" class="form-control" required id="id_identity_document_number">
                        </div>
                    </div>
                    <div class="mb-2 row">
                        <div class="col-sm-2">
                            <label for="id_password1">Password:</label>
                        </div>
                        <div class="col-sm-10 col-md-8 col-lg-6">
                            <input type="password" name="password1" autocomplete="new-password" class="form-control" required id="id_password1">
                        </div>
                        <span class="help offset-md-2">
                            <ul>
                                <li>Your password can’t be too similar to your other personal information.</li>
                                <li>Your password must contain at least 8 characters.</li>
                                <li>Your password can’t be a commonly used password.</li>
                                <li>Your password can’t be entirely numeric.</li>
                            </ul>
                        </span>
                    </div>
                    <div class="mb-2 row">
                        <div class="col-sm-2">
                            <label for="id_password2">Password confirmation:</label>
                        </div>
                        <div class="col-sm-10 col-md-8 col-lg-6">
                            <input type="password" name="password2" autocomplete="new-password" class="form-control" required id="id_password2">
                        </div>
                        <span class="help offset-md-2">Enter the same password as before, for verification.</span>
                    </div>
                    <button type="submit" class="btn btn-primary">Signup</button>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}